http:
    address: ":5000"
  
log:
    level: "info"
    format: "text"
    filename: ""
    maxsize: 500
    maxage: 7
    maxbackups: 5
    localtime: false
    compress: true    

redis:
    address: "localhost:6379"
    password: "tstpwd"
    db: 0
    maxretries: 3
    expiration: 10080m

postgres:
    host: "localhost"
    port: 5432
    database: "postgres"
    user: ""
    password: ""
    sslmode: "disable"
    maxopenconns: 10
    maxidleconns: 10
    maxlifetimconn : 10

counter:
    machineid: 1
    range: "100000-1000000"