version: "3.7"

services:
  routines-go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - config.yml
    networks:
      - routines_go_network

networks:
    routines_go_network:
